Add lint gha
ietf-ribose/bibxml-service pull request #13
Opened 2022-10-27 13:27 UTC by stefanomunarini

2022-11-03 09:51 UTC, stefanomunarini commented
#13

2022-11-08 16:36 UTC, stefanomunarini commented
After #18 is merged, tests CI will pass

2022-11-09 10:33 UTC, strogonoff requested changes

2022-11-09 10:33 UTC, strogonoff commented on docs/conf.py
> +html_js_files: List[Any] = [
I think it’s fair to say this is `List[str]`, we can avoid `Any` if possible

2022-11-09 10:33 UTC, strogonoff commented on main/api.py
> +                        external_bibitem = ext_s.get_item(docid)  # type: ignore
I think this is fixable by providing `None` as the second argument, it doesn’t change the behavior but makes it more clear to `mypy`

2022-11-09 10:33 UTC, strogonoff commented on main/api.py
> +    metric_counter = metrics.api_search_hits  # type: ignore
This ignore should be removed. I believe this is solvable by adding a type definition to `BaseCitationSearchView` like this:

```
    metric_counter: Optional[Counter] = None
```

I have this among my WIP changes, we can remove the ignore and wait until I merge this.

2022-11-09 10:33 UTC, strogonoff commented on main/api.py
> +            bibitem = source.get_item(ref.strip()).bibitem  # type: ignore
Same as before with explicit `None` as second argument

2022-11-09 10:33 UTC, strogonoff commented on main/views.py
> +    metric_counter = metrics.gui_search_hits  # type: ignore
Resolved by adding type definition on `BaseCitationSearchView` per the other comment

2022-11-09 10:33 UTC, strogonoff commented on main/views.py
> +                item = source.get_item(ref.strip())  # type: ignore
Per the other comment

2022-11-09 10:33 UTC, strogonoff commented on xml2rfc_compat/management_views.py
> +                manual_map, manual_map_item = resolve_mapping(
[The function returns a tuple (BibliographicItem, error)](https://github.com/ietf-ribose/bibxml-service/blob/32620954c44b5f948c56f2b61d068599405cc032/xml2rfc_compat/views.py#L34-L40), I don’t think this is correct after the change…

2022-11-09 10:33 UTC, strogonoff commented on xml2rfc_compat/management_views.py
> +        manual_map_item: Union[BibliographicItem, str, None]
Do we have an exact understanding of what value would it contain if it’s not a bibitem, not None, but a string?🤔

2022-11-09 10:33 UTC, strogonoff commented on xml2rfc_compat/source.py
> +    on_progress = on_progress or (lambda total, indexed: None)  # type: ignore
Interesting, mypy actually doesn’t complain on this line for me, what’s the error we’re ignoring?

(Side note: mypy allows to ignore a specific error by code, if we do it’d eliminate questions like this)

2022-11-09 13:12 UTC, stefanomunarini commented on xml2rfc_compat/source.py
> +    on_progress = on_progress or (lambda total, indexed: None)  # type: ignore
My local Mypy does not complain about this one either. However, the [GHA here](https://github.com/ietf-ribose/bibxml-service/actions/runs/3427066523/jobs/5709609721) complained about

```
xml2rfc_compat/source.py:36: error: Function "Callable[[int, int], None]" could always be true in boolean context  [truthy-function]
```

I've been looking into this, [here](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-expression-is-not-implicitly-true-in-boolean-context-truthy-bool) and [here](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-function-isn-t-used-in-boolean-context-truthy-function), and thought that, given this is going to always evaluate to True, we might just want to ignore this particular MyPy complain.

----------------------

With regards to 

> (Side note: mypy allows to ignore a specific error by code, if we do it’d eliminate questions like this)

that's exactly the reason why [I specified some flags](https://github.com/ietf-ribose/bibxml-service/pull/13/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR37) when running MyPy. @strogonoff do you think we should specified any other additional flag here?

2022-11-09 13:18 UTC, stefanomunarini commented on xml2rfc_compat/management_views.py
> +        manual_map_item: Union[BibliographicItem, str, None]
`resolve_mapping` returns a Tuple made of a BibliographicItem and a String, as for https://github.com/ietf-ribose/bibxml-service/blob/32620954c44b5f948c56f2b61d068599405cc032/xml2rfc_compat/views.py#L34-L40 
 
------------------
I guess here it should be

```
manual_map_item: Union[BibliographicItem, str]
```
instead of 
```
manual_map_item: Union[BibliographicItem, str, None]
```

2022-11-09 19:09 UTC, stefanomunarini commented on xml2rfc_compat/management_views.py
> +        manual_map_item: Union[BibliographicItem, str, None]
Updated to use python3.10 new allowed operator "**|**" .

```
manual_map_item: Union[BibliographicItem | None, str | None]
automatic_map_item: Union[BibliographicItem | None, str | None]
```

2022-11-11 13:52 UTC, stefanomunarini commented on xml2rfc_compat/management_views.py
> +                manual_map, manual_map_item = resolve_mapping(
I'm not sure I understand your comment here @strogonoff ?

2022-11-16 14:12 UTC, strogonoff commented on xml2rfc_compat/management_views.py
> +                manual_map, manual_map_item = resolve_mapping(
In your code you assign resolve_mapping() return value to manual_map and manual_map_item variables. But resolve_mapping() return value is specified as returning mapped bibliographic item and error string, no?

2022-12-13 18:05 UTC, strogonoff approved these changes
I believe the changes were addressed and we could merge this.

2022-12-13 18:21 UTC, merged