chore: add get_by_doc_id API endpoint tests
ietf-ribose/bibxml-service pull request #152
Opened 2022-03-14 15:57 UTC by stefanomunarini

2022-03-14 16:26 UTC, ronaldtse requested changes

2022-03-14 16:26 UTC, ronaldtse commented on main/tests.py
> +        url = f'{reverse("api_get_by_docid")}?docid=UNEXISTENT_DOC_ID'
"UNEXISTENT_DOC_ID" => "NONEXISTENT_DOC_ID"

2022-03-14 18:01 UTC, strogonoff commented
Let me take a look…

> On 14 Mar 2022, at 11:37 PM, Ronald Tse ***@***.***> wrote:
> 
> ﻿
> @ronaldtse requested your review on: #152 chore: add get_by_doc_id API endpoint tests.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.

2022-03-17 09:24 UTC, closed without merging

2022-03-17 09:35 UTC, ronaldtse commented
@stefanomunarini did you mean to close this, or are you making a new PR?

2022-03-17 09:49 UTC, stefanomunarini commented
@ronaldtse I've renamed the remote branch to a more generic **feat/api_tests** and the PR got closed automatically