[WIP] Unittests
ietf-ribose/bibxml-service pull request #154
Opened 2022-03-21 15:21 UTC by stefanomunarini

2022-03-22 18:58 UTC, strogonoff requested changes
Commit that changes “able” to “unable” should be reverted, the rest can be as is but let’s discuss questions raised in the comments

2022-03-22 19:04 UTC, stefanomunarini commented on xml2rfc_compat/serializer.py
> +            "Unable to construct neither <reference> nor <referencegroup>: "
Shall it be "Unable to construct either .. or .. ", then? 

To me "to be unable to do something" sounds better than "to be able to not do something".

2022-03-22 19:20 UTC, strogonoff commented on xml2rfc_compat/serializer.py
> +            "Unable to construct neither <reference> nor <referencegroup>: "
Unless there is a grammatical mistake or a typo (which I believe there is not), let’s better set it aside and focus on the tests. If we start looking into improving phrasing (as opposed to straight up typos), there is a bottomless pit of work that is secondary to current objective, so I don’t want to create a precedent.

There could be an opportunity to address this stuff in future. Even for typos I would recommend noting them and postponing for inclusion in a separate PR later.

2022-03-23 08:18 UTC, merged

2022-03-23 08:18 UTC, strogonoff commented
Discussed https://github.com/ietf-ribose/bibxml-service/pull/154/files#r832316535 1:1.

2022-03-23 08:22 UTC, strogonoff commented on xml2rfc_compat/tests.py
> +        xmlschema.assertValid(xml)  # Validate XML Schema
Filed in https://github.com/ietf-ribose/bibxml-service/issues/155